apiVersion: v1
kind: Service
metadata:
  name: {{ include "mio-console.fullname" . }}
  namespace: hidevopsio
  labels:
    app.kubernetes.io/name: {{ include "mio-console.name" . }}
    helm.sh/chart: {{ include "mio-console.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 34753
      name: http
    - port: 7575
      targetPort: http
      protocol: TCP
      name: grpc
  selector:
    app.kubernetes.io/name: {{ include "mio-console.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
