# Default values for mio-console.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hidevops/mio-console
  tag: v1.0.2
  pullPolicy: Always

nameOverride: "mio-console"
fullnameOverride: "mio-console"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: ['/hidevopsio/mioConsole']
  hosts:
    - mio-console-hidevopsio.apps.cloud2go.cn
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

git:
  url: ""

docker:
  registy: "harbor.cloud2go.cn"
  username: admin
  password: Harbor12345

deployment:
  tz: "Asia/Shanghai"
  apiVersion: ""

buildconfig:
  branch: ""
  mavenMirrorUrl: "http://nexus.cloud2go.cn/repository/maven-public/"


java:
  nodeImage: "hidevopsio/hinode-java-jar:v1.0.1"
  baseImage: "clarechu/base-image-java:0.1"

go:
  nodeImage: clarechu/hinode-go:v1.0.0
  baseImage: clarechu/base-image-java:0.1
  goProxy: http://athens.apps.cloud2go.cn
