# Default values for mio-console.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hidevopsio/mio-console
  tag: v1
  pullPolicy: Always

nameOverride: "mio-console"
fullnameOverride: "mio-console"

service:
  type: NodePort
  port: 8080

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: ['/hidevopsio/mioConsole']
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

git:
  url: "http://gitlab.vpclub.cn:8022"

docker:
  registy: "harbor.vpclub.io"
  username: admin
  password: Harbor12345

deployment:
  tz: "Asia/Shanghai"
  apiVersion: "/api/v3"

buildconfig:
  branch: "development"
  mavenMirrorUrl: "http://nexus.vpclub.cn/repository/maven-public/"


java:
  nodeImage: "docker.vpclub.cn/hidevopsio/hinode-java-jar:1.2.7"
  baseImage: "clarechu/base-image-java:0.1"

go:
  nodeImage: clarechu/hinode-go:v1.0.0
  baseImage: clarechu/base-image-java:0.1
  goProxy: http://172.16.125.1:3000
